---
title: "Data"
author: "Cassidy Bargell"
date: "4/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(rtweet)
library(httpuv)
library(gtrendsR)
library(lubridate)
library(maps)
library(pals)
library(viridis)
library(scico)
library(ggrepel)
```

```{r twitter setup}

# Twitter set-up stuff

app_name <- "clb_twitter_app"
api_key <- "qFVEvxpEi0OmgWSmuIgG7RMPx"
api_secret_key <- "4KAvZL1OFZIITkrxY7xou9dAsTurvlvrXcd5edKX7NoVJ1sGyf"
token <- create_token(
  app = "clb_twitter_app",
  consumer_key = api_key,
  consumer_secret = api_secret_key)

path_to_token <- file.path(path.expand("~"), ".twitter_token.rds")
saveRDS(token, path_to_token)
env_var <- paste0("TWITTER_PAT=", path_to_token)
cat(env_var, file = file.path(path.expand("~"), ".Renviron"), 
  fill = TRUE, append = TRUE)

readRenviron("~/.Renviron")

usa <- lookup_coords(address = "usa", apikey = "88a679312c139a94aa3d3210ef78e8a8e1a925f6")
```

```{r google}

# Find initial google search trends on rugby 

google_rugby <- gtrends(c("rugby"), geo = c("US"),
                        gprop = "web", time = "all")


# Interest by region tibble to plot

rugby_interest_by_region <- as_tibble(google_rugby$interest_by_region)
rugby_interest_by_region <- rugby_interest_by_region %>% 
  mutate(region = str_to_lower(location))

saveRDS(rugby_interest_by_region, file = "rugby-tweet/rugby_interest_by_region.RDS")

# Create map of US states


google_rugby <- gtrends(c("rugby"), geo = c("US"),
                        gprop = "web", time = "all")

saveRDS(google_rugby, file = "rugby-tweet/google_rugby.RDS")

states_map <- ggplot2::map_data("state")

saveRDS(states_map, file = "rugby-tweet/states_map.RDS")

saveRDS(google_rugby)

# Join data

rugby_merged <- merge(states_map, rugby_interest_by_region, by = "region")
rugby_merged <- rugby_interest_by_region %>% dplyr::left_join(x = ., 
                                                            y = states_map, 
                                                            by = "region")

saveRDS(rugby_merged, file = "rugby-tweet/rugby_merged.RDS")

# Create map theme so clean-up is easier

("milestone-6/map_theme.R")

map_theme = function() {
    theme(axis.title = element_blank()) +
    theme(axis.text = element_blank()) +
    theme(axis.ticks = element_blank()) + 
    theme(legend.title = element_blank()) +
  theme(panel.grid.major = element_blank())
}

# Plot map 

plot_rgsearch <- ggplot(rugby_merged, aes(x = long, y = lat)) +
  geom_polygon(aes(group = group, 
                   fill = log(hits)), 
               colour = "white") +
  scale_fill_viridis_c(option = "plasma",
                       direction = -1) +
  theme_minimal() + 
  labs(title = "Google Search Hits for 'Rugby' Since 2004", 
       subtitle = "Search Hits Normalized to Compare Relative Popularity",
       caption = "Google Trends: Search results are normalized to the time and
       location of a query. Each data point is divided by the total searches of
       the geography and time range it represents to compare relative popularity.") +
  map_theme()
```

